version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ./.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ./.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  users:
    volumes:
        - ./usuarios/:/mnt/
    build: ./usuarios
    working_dir: /backend/
    command: sh run.sh
  products:
    volumes:
        - ./productos/:/mnt/
    build: ./productos
    working_dir: /backend/
    command: sh run.sh
  orders:
    volumes:
        - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: sh run.sh
    depends_on:
      - users
      - products
      - rabbitmq
  worker:
    volumes:
      - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: python worker.py
    depends_on:
      - users
      - products
      - rabbitmq

  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - orders
        - worker