version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  jwt:
    volumes:
        - ./jwt/:/mnt/
    build: ./jwt
    working_dir: /backend/
    command: sh run.sh
  acl:
    volumes:
        - ./acl/:/mnt/
    build: ./acl
    working_dir: /backend/
    command: sh run.sh
  users:
    volumes:
        - ./usuarios/:/mnt/
    build: ./usuarios
    working_dir: /backend/
    command: sh run.sh
  products:
    volumes:
        - ./productos/:/mnt/
    build: ./productos
    working_dir: /backend/
    command: sh run.sh
  orders:
    volumes:
        - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: sh run.sh
    depends_on:
      - users
      - products
      - redis
  worker:
    volumes:
      - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: rq worker -u 'redis://redis/1'
    depends_on:
      - users
      - products
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 5000:443
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/localhost.crt:/etc/ssl/certs/localhost.crt
        - ./nginx/localhost.key:/etc/ssl/private/localhost.key
    depends_on:
        - orders
        - worker
        - jwt
