version: "3.2"
services:
  redis:
    image: redis
    volumes: 
      - ./data:/data
  users:
    volumes:
        - ./usuarios/:/mnt/
    build: ./usuarios
    working_dir: /backend/
    command: sh run.sh
  products:
    volumes:
        - ./productos/:/mnt/
    build: ./productos
    working_dir: /backend/
    command: sh run.sh
  orders:
    volumes:
        - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: sh run.sh
    depends_on:
      - users
      - products
      - redis
  worker:
    volumes:
      - ./ordenes/:/mnt/
    build: ./ordenes
    working_dir: /backend/
    command: rq worker -u 'redis://redis/0'
    depends_on:
      - users
      - products
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 5000:80
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - orders
        - worker
